/************************************************************\
 **  Copyright (c) 2011-2022 Anlogic, Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	D:/FPGA/CTRL_BOARD_MASTER/al_ip/lpm_unsigned_mult8x32.v
 ** Date	:	2023 09 08
 ** TD version	:	5.6.56362
\************************************************************/

`timescale 1ns / 1ps

module lpm_unsigned_mult8x32 ( p, a, b );

	output [41:0] p;

	input  [9:0] a;
	input  [31:0] b;



	EG_LOGIC_MULT #( .INPUT_WIDTH_A(10),
				.INPUT_WIDTH_B(32),
				.OUTPUT_WIDTH(42),
				.INPUTFORMAT("UNSIGNED"),
				.INPUTREGA("DISABLE"),
				.INPUTREGB("DISABLE"),
				.OUTPUTREG("DISABLE"),
				.IMPLEMENT("AUTO")
			)
			inst(
				.a(a),
				.b(b),
				.p(p),
				.cea(1'b0),
				.ceb(1'b0),
				.cepd(1'b0),
				.clk(1'b0),
				.rstan(1'b0),
				.rstbn(1'b0),
				.rstpdn(1'b0)
			);


endmodule